### ISSUE TITLE
Enable kerberos authentication for PowerShell

### ISSUE THREAD

**Issue by abhi1202** [PowerShell/psl-omi-provider#102]
OMI is providing kerberos authentication but using PSL-OMI  i am not able to do remoting from linux to windows.

**Comment by JumpingYang001** [comment]
You need to wait new release package under https://github.com/PowerShell/psl-omi-provider/releases

**Comment by abhi1202** [comment]
what are the timelines to support it.

**Comment by JumpingYang001** [comment]
Maybe @daxian-dbw can answer this question, thanks.

**Comment by dantraMSFT** [comment]
This should be fixed by the latest OMI and PSRP releases. both now depend on libgssapi_krb5 2.
https://github.com/PowerShell/psl-omi-provider/releases/tag/v1.4.1-28
