### ISSUE TITLE
New-PSSession to itself failed

### ISSUE THREAD

**Issue by simonfangyingzhang** [PowerShell/psl-omi-provider#105]
Hi Guru,

New-PSSession to itself failed, I could not find the cause, could you please help? really appericate

PS /root> New-PSSession -Credential $credential -ComputerName 127.0.0.1 -Verbose -Authentication Basic -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipRevocationCheck -SkipCNCheck)                               
New-PSSession : [127.0.0.1] Connecting to remote server 127.0.0.1 failed with the following error message : A general error occurred, not covered by a more specific error code. For more information, see the 
about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ New-PSSession -Credential $credential -ComputerName 127.0.0.1 -Verbos ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : 1,PSSessionOpenFailed
PS /root> 

root@pek2-gosv-16-dhcp167:~# sudo service omid status
● omid.service - OMI CIM Server
   Loaded: loaded (/lib/systemd/system/omid.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2017-10-28 09:45:26 UTC; 9min ago
  Process: 4175 ExecStop=/opt/omi/bin/omiserver -s (code=exited, status=0/SUCCESS)
  Process: 4219 ExecStart=/opt/omi/bin/omiserver -d (code=exited, status=0/SUCCESS)
  Process: 4179 ExecStartPre=/opt/omi/bin/support/installssllinks (code=exited, status=0/SUCCESS)
 Main PID: 4223 (omiserver)
    Tasks: 5 (limit: 512)
   Memory: 3.4M
      CPU: 362ms
   CGroup: /system.slice/omid.service
           ├─4223 /opt/omi/bin/omiserver -d
           ├─4224 /opt/omi/bin/omiengine -d --logfilefd 3 --socketpair 9
           ├─4254 /opt/omi/bin/omiagent 9 10 --destdir / --providerdir /opt/omi/lib --loglevel WARNING
           ├─4363 /opt/omi/bin/omiagent 9 10 --destdir / --providerdir /opt/omi/lib --loglevel WARNING
           └─4378 /opt/omi/bin/omiagent 9 10 --destdir / --providerdir /opt/omi/lib --loglevel WARNING

Oct 28 09:45:26 pek2-gosv-16-dhcp167 systemd[1]: Starting OMI CIM Server...
Oct 28 09:45:26 pek2-gosv-16-dhcp167 systemd[1]: omid.service: PID file /var/opt/omi/run/omiserver.pid not readable (yet?) after start: No such file or direc
Oct 28 09:45:26 pek2-gosv-16-dhcp167 systemd[1]: omid.service: Supervising process 4223 which is not our child. We'll most likely not notice when it exits.
Oct 28 09:45:26 pek2-gosv-16-dhcp167 systemd[1]: Started OMI CIM Server.

root@pek2-gosv-16-dhcp167:~#  cat /var/opt/omi/log/omiserver.log
2017/10/28 08:04:52 [1980,1980] ERROR: null(0): EventId=20135 Priority=ERROR NTLM Credentials file does not exist or invalid permissions: null
2017/10/28 08:08:12 [1981,1981] WARNING: null(0): EventId=30107 Priority=WARNING Sock_Read: Error 9
2017/10/28 08:08:12 [1981,1981] WARNING: null(0): EventId=30112 Priority=WARNING Socket: 0xc31c80, Error: 1 while reading header

2017/10/28 08:08:12 [1981,1981] WARNING: null(0): EventId=30214 Priority=WARNING Selector_RemoveHandler: selector=0x5d1fc8, handler=0xc31c80, name=null NOT REGISTERED
2017/10/28 08:08:14 [2571,2571] ERROR: null(0): EventId=20135 Priority=ERROR NTLM Credentials file does not exist or invalid permissions: null
2017/10/28 08:32:40 [2572,2572] WARNING: null(0): EventId=30107 Priority=WARNING Sock_Read: Error 9
2017/10/28 08:32:40 [2572,2572] WARNING: null(0): EventId=30112 Priority=WARNING Socket: 0x15102e0, Error: 1 while reading header

2017/10/28 08:32:40 [2572,2572] WARNING: null(0): EventId=30214 Priority=WARNING Selector_RemoveHandler: selector=0x5d1fc8, handler=0x15102e0, name=null NOT REGISTERED
2017/10/28 09:37:50 [2572,2572] WARNING: null(0): EventId=30107 Priority=WARNING Sock_Read: Error 9
2017/10/28 09:37:50 [2572,2572] WARNING: null(0): EventId=30112 Priority=WARNING Socket: 0x1513350, Error: 1 while reading header

2017/10/28 09:37:50 [2572,2572] WARNING: null(0): EventId=30214 Priority=WARNING Selector_RemoveHandler: selector=0x5d1fc8, handler=0x1513350, name=null NOT REGISTERED
2017/10/28 09:39:30 [3927,3927] ERROR: null(0): EventId=20135 Priority=ERROR NTLM Credentials file does not exist or invalid permissions: null
2017/10/28 09:40:10 [3998,3998] ERROR: null(0): EventId=20135 Priority=ERROR NTLM Credentials file does not exist or invalid permissions: null
2017/10/28 09:42:09 [4093,4093] ERROR: null(0): EventId=20135 Priority=ERROR NTLM Credentials file does not exist or invalid permissions: null
2017/10/28 09:45:26 [4223,4223] ERROR: null(0): EventId=20135 Priority=ERROR NTLM Credentials file does not exist or invalid permissions: null
root@pek2-gosv-16-dhcp167:~#

**Comment by simonfangyingzhang** [comment]
btw, from this linux to windows new-pssession can be success,

looks like omid wrong on this linux? but unable to fix ti

**Comment by simonfangyingzhang** [comment]
looks like similar to #101? I am using 6.0.0 beta9

PS /root> $PSVersionTable.PSVersion                                                                                                                        

Major Minor Patch Label 
----- ----- ----- ----- 
    6     0     0 beta.9
PS /root>

**Comment by simonfangyingzhang** [comment]
revert to 6.0.0 beta1 and it can work,

PS /root>  $PSVersionTable.PSVersion                                                                                                                                                                                             

Major Minor Patch Label
----- ----- ----- -----
    6     0     0 beta 


PS /root> New-PSSession -Credential $credential -ComputerName 127.0.0.1 -Verbose -Authentication Basic -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipRevocationCheck -SkipCNCheck)                               

 Id Name            ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            ------------    ------------    -----         -----------------     ------------
  2 WinRM2          127.0.0.1       RemoteMachine   Opened        Microsoft.PowerShell     Available


PS /root>

**Comment by 4rtorias** [comment]
@simonfangyingzhang You are seriously a lifesaver! I was trying to figure this out on the latest version for half a day.
