### ISSUE TITLE
Remove Pester submodule

### ISSUE THREAD

**Issue by andschwa** [PowerShell/psl-omi-provider#50]
@JumpingYang001 confirmed internally that no changes will be made to Pester, and that the PowerShell 6.0 packages will be installed for testing purposes. As these packages include the Pester PowerShell module, the submodule introduced in #42 is unnecessary.

**Comment by JumpingYang001** [comment]
@andschwa ,yeah, if Pester are embedded into PowerShell for all the lifecycle, we are ok to remove it.

**Comment by JumpingYang001** [comment]
Another question, currently, once we install latest released PowerShell, we can directly call "Invoke-Pester .\test\PSRP.Tests.ps1 " without running "Import-Module Pester", right?

**Comment by JumpingYang001** [comment]
I have try run powershell, and can directly call "Invoke-Pester .\test\PSRP.Tests.ps1", I will remove the submodule, thanks.

**Comment by JumpingYang001** [comment]
@andschwa could you help to review and merge #54 ? thank you!
