### ISSUE TITLE
Communicate features in progress

### ISSUE THREAD

**Issue by andschwa** [PowerShell/psl-omi-provider#65]
Hello,

I believe that @paulcallen, @palladia, and @yakman2020 have a few features in progress to eliminate these two required steps:

```
winrm set winrm/config/Service @{AllowUnencrypted="true"}
winrm set winrm/config/Service/Auth @{Basic="true"}
```

I'm [being asked](https://twitter.com/bielawb/status/808580938317918208) for progress on that, and realized that we don't have a list anywhere public of features currently in progress. Is this something we could provide, either in the readme or in a set of issues?

**Comment by paulcallen** [comment]
We are currently finalizing the SPNEGO NTLM support for the platforms that can support it. OSX is one platform that cannot, so we will be looking at other solutions to that. Older platforms do not make it easy to interop with Windows, and sometimes we need new patches to be installed or even patches to be built and installed. We will post instructions on enabling spnego ntlm on the Linux platforms that can support it when we are done.

**Comment by aalblas** [comment]
Good news on the SPNEGO NTLM, is there an ETA for when kerberos will work with the AllowUnencrypted=false

**Comment by paulcallen** [comment]
SPNEGO NTLM will do encryption over HTTP, so no more allow-unencrypted and basic auth, and no need for an SSL server cert.

In terms of Kerberos we are looking into it and do understand what needs to be done, but I cannot commit to when it will be available yet.

I have a question for @aalblas  and any others who are wanting Kerberos. What kind of environments are you wanting to use Kerberos on? Is it OSX, Centos, Ubuntu, or what? What kind of KDC are you connected to, Windows AD or some third party KDC? I am assuming you are wanting to connect from OSX/Linux to Windows mostly, or is the other way as equally important.

**Comment by aalblas** [comment]
Primary use case for us is from Linux (Redhat & CentOS) to Windows using Windows AD as KDC.

**Comment by gorankor** [comment]
Similar as above, from Centos 7 to Windows using Windows AD as KDC.

**Comment by paulcallen** [comment]
Thanks @aalblas and @gorankor for your feedback.

**Comment by paulcallen** [comment]
For CentOS 7, is that 7.3?

**Comment by gorankor** [comment]
The exact version is not particularly important for us, at least yet - so yes, it can be 7.3 if that's the one that helps. Right now we're on 7.2.

**Comment by gorankor** [comment]
Sorry for abusing this issue - not sure where else would be more appropriate. I tried to write an example which would run on a Linux system, and execute a command remotely on a Windows system. libpsrpclient.so seems to implement the API-s from here so I relied on that (not all functions are available, i.e. some variants without "Ex" are missing):

https://msdn.microsoft.com/en-us/library/dd891121(v=vs.85).aspx

The documentation for WSManCreateShellEx() says it needs resourceUri as a parameter, and if WSMAN_CMDSHELL_URI is specified, this is a cmd.exe shell (this string is defined as "/cmd").

If I do that, the remote server always responds with:

-----------------------
The SOAP XML in the message does not match the corresponding XML schema definition. Change the XML and retry.
The Windows Remote Shell cannot process the request. The SOAP packet contains an element Shell that is invalid. Retry the request with the correct XML element.
-----------------------

If I compare generated XML to this, it's completely different:

https://msdn.microsoft.com/en-us/library/cc251739.aspx

If I specify a different resourceUri ("http://schemas.microsoft.com/powershell/Microsoft.PowerShell"), then I get past that, but that has other issues:

- "protocolversion" needs to be present in the options (the only way to do that is to construct the "options" parameter manually, i.e. there are no helpers)
- if I look at how powershell calls WSManRunShellCommandEx(), it passes base64 encoded argument; string, while if I fill in "args" array with arguments, I get back an errors ("Invalid length for a Base-64 char array or string.") or, if I later try to read out command's output, I get nothing back (the callback for this function says there was no error and I also see <rsp:ExitCode>0</rsp:ExitCode> in XML)

So my questions are:

1. Is libpsrpclient.so supposed to work for WSMAN_CMDSHELL_URI and generate valid SOAP XML?

2. If not, is this planned for the future or not at all?

3. If not, how is one supposed to generate valid "args" for WSManRunShellCommandEx() - are there any helpers, or is the user expected to manually construct valid XML (like documented here https://msdn.microsoft.com/en-us/library/dd357801.aspx )?  The same question also applies to WSManCreateShellEx() and its "createXml" parameter.

Many thanks.

**Comment by paulcallen** [comment]
@gorankor I am a little confused as to what you are trying to achieve here. The work done in this project is completely focused on the work needed for PowerShell PSRP remoting only. Are you trying to use the APIs directly to so remote commands themselves outside of PowerShell itself? If so that is not supported. The only scenario supported is PowerShell remoting. If you are trying to do something specific in PowerShell then can you be more specific so I can better understand the scenario?

**Comment by gorankor** [comment]
To clarify, I wanted to use this outside of the PowerShell itself, but based on what you said this will have to be reconsidered.

**Comment by paulcallen** [comment]
Indeed. The scope of my project was PowerShell itself, not supporting the full shell API. That said there would not be a great deal of differences, but it is still out of scope for our team. sorry.

**Comment by Happycoil** [comment]
Do you have a roadmap for encrypted remoting from OS X/macOS?

**Comment by paulcallen** [comment]
We are actively working on it. OSX is being a bit of a pain again even with Kerberos. Dealing with those issues, finishing up the coding, then testing I would imagine a month, maybe a little more. Don't hold me to this though as these interop issues can be really painful and unpredictable.

**Comment by paulcallen** [comment]
we are doing final testing of OMI for Kerberos authentication and encryption.  ETA for OMI release is by then of July. We will coordinate with the PowerShell team to get those changes included in the PowerShell package to give client-side support remoting to Windows.

**Comment by davidaah** [comment]
hi all! just wanted to see if there is an updated timeline for Kerberos auth on macOS or linux as well as timeline for integration of this support in powershell?

**Comment by paulcallen** [comment]
Client (remoting from osx and linux): omi has officially released the Kerberos support.  PowerShell will need to pick up a new libmi nuget package from our build share and then pull that into their build and release. Server (remoting into Linux/Windows): omi can be upgraded and you will get Kerberos support.
You can take a look at http://GitHub.com/microsoft/omi readme to see some of the configuration needed to make this work based on our experiences.

**Comment by andyleejordan** [comment]
There's been no movement on this issue for three years, and since I opened it, I'm going to close it 😉
