### ISSUE TITLE
NTLM authentication over SPNEGO documentation for PowerShell and OMI

### ISSUE THREAD

**Issue by paulcallen** [PowerShell/psl-omi-provider#75]
@yakman2020 is working on this

**Comment by yakman2020** [comment]
Not necessary. I’ll fix right now.

I’ll take a look at the NegoNoCreds path encryption. We usually test with NegoWithCreds, but the paths are quite similar.

**Comment by paulcallen** [comment]
[OMI NTLM setup documents](https://github.com/Microsoft/omi/blob/master/Unix/doc/setup-ntlm-omi.md)
