### ISSUE TITLE
publish package to packages.microsoft.com

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/psl-omi-provider#78]

**Comment by paulcallen** [comment]
we are certainly investigating this for both omi and psrp provider.

**Comment by bielawb** [comment]
And what about Linux DSC? Would also makes sense to have it published to the repository.

**Comment by SteveL-MSFT** [comment]
CC @Indhukrishna

**Comment by paulcallen** [comment]
provider and omi has been published. See readme for details.
