### ISSUE TITLE
make "/bin/ld cannot find -lpam / -lssl / -lcrypto"

### ISSUE THREAD

**Issue by jamesbannan** [PowerShell/psl-omi-provider#98]
I'm attempting to compile the psl-omi-provider on CentOS 7.3.  When I clone down the repository and run either "make debug" or "make release", I get the following error in the "Performing Building OMI" section:

========================= Performing Building OMI
( cd /home/james/downloads/psl-omi-provider/omi/Unix; make -f build.mak )
make[2]: Entering directory `/home/james/downloads/psl-omi-provider/omi/Unix'
make[3]: Entering directory `/home/james/downloads/psl-omi-provider/omi/Unix/chkshlib'
mkdir -p /home/james/downloads/psl-omi-provider/omi/Unix/output/bin
g++ -o /home/james/downloads/psl-omi-provider/omi/Unix/output/bin/chkshlib /home/james/downloads/psl-omi-provider/omi/Unix/output/obj/chkshlib/chkshlib.o -L/home/james/downloads/psl-omi-provider/omi/Unix/output/lib -L      -lpthread -ldl -lpam -lssl -lcrypto  -Wl,-rpath=/opt/omi/lib
/bin/ld: cannot find -lpam
/bin/ld: cannot find -lssl
/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
make[3]: *** [/home/james/downloads/psl-omi-provider/omi/Unix/output/bin/chkshlib] Error 1
make[3]: Leaving directory `/home/james/downloads/psl-omi-provider/omi/Unix/chkshlib'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/james/downloads/psl-omi-provider/omi/Unix'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/james/downloads/psl-omi-provider/omi/Unix'
make: *** [release] Error 2

**Comment by paulcallen** [comment]
you need to install the prerequisites. The readme for the project points to [omi dependencies](https://github.com/Microsoft/Build-omi/blob/master/README.md#dependencies-to-build-a-native-package)
